  -- ====================================================================================
  -- BARBERSHOP BOOKING - COMBINED DATABASE MIGRATIONS SCRIPT (IDEMPOTENT & ROBUST)
  -- Generated by combining all 14 migration files in chronological order.
  -- Paste this entire script into your Supabase SQL Editor and click "Run".
  -- ====================================================================================

  -- ====================================================================================
  -- MIGRATION 1: 20260615001715_875d8897-eb99-45fb-8243-b344292f5507.sql
  -- ====================================================================================

  -- ============ ROLES ============
  DO $$ BEGIN
    CREATE TYPE public.app_role AS ENUM ('admin', 'staff');
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;

  CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role app_role NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, role)
  );
  GRANT SELECT ON public.user_roles TO authenticated;
  GRANT ALL ON public.user_roles TO service_role;
  ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

  CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
  RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
  AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;

  DROP POLICY IF EXISTS "users read own roles" ON public.user_roles;
  CREATE POLICY "users read own roles" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());

  DROP POLICY IF EXISTS "admins manage roles" ON public.user_roles;
  CREATE POLICY "admins manage roles" ON public.user_roles FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- First signup becomes admin
  CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE role = 'admin') THEN
      INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'admin') ON CONFLICT DO NOTHING;
    ELSE
      INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'staff') ON CONFLICT DO NOTHING;
    END IF;
    RETURN NEW;
  END; $$;

  DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
  CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

  -- ============ SERVICES ============
  CREATE TABLE IF NOT EXISTS public.services (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'Haircut',
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    duration_minutes INT NOT NULL DEFAULT 30,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.services TO authenticated;
  GRANT ALL ON public.services TO service_role;
  ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage services" ON public.services;
  CREATE POLICY "admins manage services" ON public.services FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ BARBERS ============
  CREATE TABLE IF NOT EXISTS public.barbers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    specialization TEXT,
    experience_years INT NOT NULL DEFAULT 0,
    bio TEXT,
    rating NUMERIC(3,2) NOT NULL DEFAULT 5.0,
    avatar_url TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.barbers TO authenticated;
  GRANT ALL ON public.barbers TO service_role;
  ALTER TABLE public.barbers ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage barbers" ON public.barbers;
  CREATE POLICY "admins manage barbers" ON public.barbers FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ PORTFOLIO ============
  CREATE TABLE IF NOT EXISTS public.barber_portfolio (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    barber_id UUID NOT NULL REFERENCES public.barbers(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    caption TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.barber_portfolio TO authenticated;
  GRANT ALL ON public.barber_portfolio TO service_role;
  ALTER TABLE public.barber_portfolio ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage portfolio" ON public.barber_portfolio;
  CREATE POLICY "admins manage portfolio" ON public.barber_portfolio FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ BOOKINGS ============
  DO $$ BEGIN
    CREATE TYPE public.booking_status AS ENUM ('pending','confirmed','in_progress','completed','cancelled','no_show');
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;

  CREATE TABLE IF NOT EXISTS public.bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reference TEXT NOT NULL UNIQUE DEFAULT ('BK-' || lpad((floor(random()*100000))::text, 5, '0')),
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    customer_email TEXT,
    barber_id UUID REFERENCES public.barbers(id) ON DELETE SET NULL,
    service_id UUID REFERENCES public.services(id) ON DELETE SET NULL,
    booking_date DATE NOT NULL,
    start_time TIME NOT NULL,
    status booking_status NOT NULL DEFAULT 'pending',
    price NUMERIC(10,2) NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.bookings TO authenticated;
  GRANT ALL ON public.bookings TO service_role;
  ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage bookings" ON public.bookings;
  CREATE POLICY "admins manage bookings" ON public.bookings FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ WALK-INS ============
  DO $$ BEGIN
    CREATE TYPE public.walkin_status AS ENUM ('waiting','in_progress','completed','cancelled');
  EXCEPTION
    WHEN duplicate_object THEN null;
  END $$;

  CREATE TABLE IF NOT EXISTS public.walk_ins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    service_id UUID REFERENCES public.services(id) ON DELETE SET NULL,
    barber_id UUID REFERENCES public.barbers(id) ON DELETE SET NULL,
    status walkin_status NOT NULL DEFAULT 'waiting',
    estimated_wait_minutes INT NOT NULL DEFAULT 15,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.walk_ins TO authenticated;
  GRANT ALL ON public.walk_ins TO service_role;
  ALTER TABLE public.walk_ins ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage walkins" ON public.walk_ins;
  CREATE POLICY "admins manage walkins" ON public.walk_ins FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ SCHEDULES ============
  CREATE TABLE IF NOT EXISTS public.schedules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    barber_id UUID NOT NULL REFERENCES public.barbers(id) ON DELETE CASCADE,
    day_of_week INT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    start_time TIME NOT NULL DEFAULT '09:00',
    end_time TIME NOT NULL DEFAULT '18:00',
    is_off BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (barber_id, day_of_week)
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.schedules TO authenticated;
  GRANT ALL ON public.schedules TO service_role;
  ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage schedules" ON public.schedules;
  CREATE POLICY "admins manage schedules" ON public.schedules FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  CREATE TABLE IF NOT EXISTS public.time_off (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    barber_id UUID NOT NULL REFERENCES public.barbers(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.time_off TO authenticated;
  GRANT ALL ON public.time_off TO service_role;
  ALTER TABLE public.time_off ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage timeoff" ON public.time_off;
  CREATE POLICY "admins manage timeoff" ON public.time_off FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ HOLIDAYS ============
  CREATE TABLE IF NOT EXISTS public.holidays (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    holiday_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.holidays TO authenticated;
  GRANT ALL ON public.holidays TO service_role;
  ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage holidays" ON public.holidays;
  CREATE POLICY "admins manage holidays" ON public.holidays FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ NOTIFICATIONS ============
  CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'info',
    is_read BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO authenticated;
  GRANT ALL ON public.notifications TO service_role;
  ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage notifications" ON public.notifications;
  CREATE POLICY "admins manage notifications" ON public.notifications FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  -- ============ SETTINGS ============
  CREATE TABLE IF NOT EXISTS public.shop_settings (
    id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    shop_name TEXT NOT NULL DEFAULT 'Modern Cuts Barbershop',
    shop_email TEXT,
    shop_phone TEXT,
    shop_address TEXT,
    open_time TIME NOT NULL DEFAULT '09:00',
    close_time TIME NOT NULL DEFAULT '20:00',
    payment_cash BOOLEAN NOT NULL DEFAULT true,
    payment_gcash BOOLEAN NOT NULL DEFAULT true,
    payment_maya BOOLEAN NOT NULL DEFAULT false,
    payment_card BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );
  GRANT SELECT, INSERT, UPDATE, DELETE ON public.shop_settings TO authenticated;
  GRANT ALL ON public.shop_settings TO service_role;
  ALTER TABLE public.shop_settings ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "admins manage settings" ON public.shop_settings;
  CREATE POLICY "admins manage settings" ON public.shop_settings FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));

  INSERT INTO public.shop_settings (id, shop_name, shop_email, shop_phone, shop_address)
  VALUES (1, 'Modern Cuts Barbershop', 'hello@moderncuts.ph', '+63 917 555 0100', '123 Mabini St, Makati City')
  ON CONFLICT (id) DO NOTHING;

  -- ============ SEED DATA ============
  INSERT INTO public.services (name, description, category, price, duration_minutes)
  SELECT name, description, category, price, duration_minutes FROM (VALUES
    ('Classic Haircut','Traditional cut with scissors and clippers','Haircut',350,30),
    ('Skin Fade','Precision skin fade with detailed taper','Haircut',450,45),
    ('Beard Trim','Beard shape-up and line-up','Beard',250,20),
    ('Hot Towel Shave','Straight razor shave with hot towel','Shave',600,40),
    ('Hair + Beard Combo','Full haircut and beard service','Combo',750,60),
    ('Kids Cut','Haircut for kids under 12','Haircut',300,30)
  ) AS v(name, description, category, price, duration_minutes)
  WHERE NOT EXISTS (SELECT 1 FROM public.services WHERE name = v.name);

  INSERT INTO public.barbers (id, name, specialization, experience_years, bio, rating, avatar_url, is_active) VALUES
    ('11111111-1111-1111-1111-111111111111','Marco Reyes','Classic Fades & Skin Fades',8,'Senior barber specializing in precision fades and beard sculpting.',4.9,'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80',true),
    ('22222222-2222-2222-2222-222222222222','Jules Santos','Modern Cuts & Textured Styles',6,'Loves crafting textured crops, curtains, and modern pompadours.',4.8,'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&q=80',true),
    ('33333333-3333-3333-3333-333333333333','Eli Mendoza','Hot Towel Shaves & Beard Care',10,'Old-school straight razor shaves and beard grooming specialist.',4.7,'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',true),
    ('44444444-4444-4444-4444-444444444444','Sam Villar','Kids Cuts & Family Styles',4,'Patient and friendly — a favorite with first-time customers.',4.6,'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&q=80',true)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO public.barber_portfolio (barber_id, image_url)
  SELECT barber_id::uuid, image_url FROM (VALUES
    ('11111111-1111-1111-1111-111111111111','https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=600&q=80'),
    ('11111111-1111-1111-1111-111111111111','https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&q=80'),
    ('11111111-1111-1111-1111-111111111111','https://images.unsplash.com/photo-1622286342621-4bd786c2447c?w=600&q=80'),
    ('22222222-2222-2222-2222-222222222222','https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=600&q=80'),
    ('22222222-2222-2222-2222-222222222222','https://images.unsplash.com/photo-1521490878406-d77df8560b3a?w=600&q=80'),
    ('33333333-3333-3333-3333-333333333333','https://images.unsplash.com/photo-1517832606299-7ae9b720a186?w=600&q=80'),
    ('33333333-3333-3333-3333-333333333333','https://images.unsplash.com/photo-1593702275687-f8b402bf1fb5?w=600&q=80'),
    ('44444444-4444-4444-4444-444444444444','https://images.unsplash.com/photo-1622287162716-f311baa1a2b8?w=600&q=80')
  ) AS v(barber_id, image_url)
  WHERE NOT EXISTS (SELECT 1 FROM public.barber_portfolio WHERE image_url = v.image_url);

  -- Default schedules: all barbers Mon-Sat 9-18, Sun off
  INSERT INTO public.schedules (barber_id, day_of_week, start_time, end_time, is_off)
  SELECT b.id, d, '09:00','18:00', (d = 0)
  FROM public.barbers b CROSS JOIN generate_series(0,6) d
  ON CONFLICT (barber_id, day_of_week) DO NOTHING;

  -- Sample bookings (use a service join via subqueries)
  INSERT INTO public.bookings (customer_name, customer_phone, barber_id, service_id, booking_date, start_time, status, price)
  SELECT customer_name, customer_phone, barber_id::uuid, service_id, booking_date::date, start_time::time, status::booking_status, price FROM (VALUES
    ('Daniel Cruz','+63 917 111 2233','11111111-1111-1111-1111-111111111111',(SELECT id FROM public.services WHERE name='Skin Fade' LIMIT 1), CURRENT_DATE, '10:00','confirmed',450),
    ('Anton Lim','+63 917 222 3344','22222222-2222-2222-2222-222222222222',(SELECT id FROM public.services WHERE name='Beard Trim' LIMIT 1), CURRENT_DATE, '10:30','pending',250),
    ('Rafael Tan','+63 917 333 4455','33333333-3333-3333-3333-333333333333',(SELECT id FROM public.services WHERE name='Hot Towel Shave' LIMIT 1), CURRENT_DATE, '11:15','in_progress',600),
    ('Miguel Reyes','+63 917 444 5566','11111111-1111-1111-1111-111111111111',(SELECT id FROM public.services WHERE name='Hair + Beard Combo' LIMIT 1), CURRENT_DATE, '12:00','confirmed',750),
    ('Jacob Uy','+63 917 555 6677','22222222-2222-2222-2222-222222222222',(SELECT id FROM public.services WHERE name='Kids Cut' LIMIT 1), CURRENT_DATE, '13:00','confirmed',300),
    ('Paolo Garcia','+63 917 666 7788','11111111-1111-1111-1111-111111111111',(SELECT id FROM public.services WHERE name='Skin Fade' LIMIT 1), CURRENT_DATE - 1, '16:30','completed',450),
    ('Vince Aquino','+63 917 777 8899','33333333-3333-3333-3333-333333333333',(SELECT id FROM public.services WHERE name='Beard Trim' LIMIT 1), CURRENT_DATE - 1, '15:00','completed',250),
    ('Leo Bautista','+63 917 888 9900','22222222-2222-2222-2222-222222222222',(SELECT id FROM public.services WHERE name='Hair + Beard Combo' LIMIT 1), CURRENT_DATE - 1, '14:00','cancelled',750),
    ('Niko Flores','+63 917 999 0011','11111111-1111-1111-1111-111111111111',(SELECT id FROM public.services WHERE name='Hot Towel Shave' LIMIT 1), CURRENT_DATE - 1, '11:00','no_show',600)
  ) AS v(customer_name, customer_phone, barber_id, service_id, booking_date, start_time, status, price)
  WHERE NOT EXISTS (SELECT 1 FROM public.bookings WHERE customer_name = v.customer_name);

  INSERT INTO public.walk_ins (customer_name, customer_phone, service_id, status, estimated_wait_minutes)
  SELECT customer_name, customer_phone, service_id, status::walkin_status, estimated_wait_minutes FROM (VALUES
    ('Walk-in Carlos','+63 917 100 0001',(SELECT id FROM public.services WHERE name='Classic Haircut' LIMIT 1),'waiting',15),
    ('Walk-in Jorge','+63 917 100 0002',(SELECT id FROM public.services WHERE name='Beard Trim' LIMIT 1),'waiting',25)
  ) AS v(customer_name, customer_phone, service_id, status, estimated_wait_minutes)
  WHERE NOT EXISTS (SELECT 1 FROM public.walk_ins WHERE customer_name = v.customer_name);

  INSERT INTO public.notifications (title, message, type)
  SELECT title, message, type FROM (VALUES
    ('New booking received','Daniel Cruz booked a Skin Fade for today at 10:00','booking'),
    ('Walk-in waiting','Carlos is waiting for a Classic Haircut','walkin'),
    ('Booking cancelled','Leo Bautista cancelled his Hair + Beard Combo','cancellation')
  ) AS v(title, message, type)
  WHERE NOT EXISTS (SELECT 1 FROM public.notifications WHERE title = v.title);


  -- ====================================================================================
  -- MIGRATION 2: 20260615001740_d43213a0-7b51-42d8-8907-6e5c2e43d708.sql
  -- ====================================================================================

  REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC, anon;
  REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
  GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;


  -- ====================================================================================
  -- MIGRATION 3: 20260618002215_c25aecd0-b7f7-4598-a63c-1c9dff4ce1dd.sql
  -- ====================================================================================

  -- 1) Add user_id to bookings (nullable for guests)
  ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;
  CREATE INDEX IF NOT EXISTS bookings_user_id_idx ON public.bookings(user_id);

  -- 2) Public read access (anon + authenticated) for catalog tables
  GRANT SELECT ON public.services TO anon;
  GRANT SELECT ON public.barbers TO anon;
  GRANT SELECT ON public.barber_portfolio TO anon;
  GRANT SELECT ON public.schedules TO anon;
  GRANT SELECT ON public.time_off TO anon;
  GRANT SELECT ON public.holidays TO anon;
  GRANT SELECT ON public.shop_settings TO anon;
  GRANT SELECT ON public.services TO authenticated;
  GRANT SELECT ON public.barbers TO authenticated;
  GRANT SELECT ON public.barber_portfolio TO authenticated;
  GRANT SELECT ON public.schedules TO authenticated;
  GRANT SELECT ON public.time_off TO authenticated;
  GRANT SELECT ON public.holidays TO authenticated;
  GRANT SELECT ON public.shop_settings TO authenticated;

  DROP POLICY IF EXISTS "public read services" ON public.services;
  CREATE POLICY "public read services" ON public.services FOR SELECT TO anon, authenticated USING (is_active = true);

  DROP POLICY IF EXISTS "public read barbers" ON public.barbers;
  CREATE POLICY "public read barbers" ON public.barbers FOR SELECT TO anon, authenticated USING (is_active = true);

  DROP POLICY IF EXISTS "public read portfolio" ON public.barber_portfolio;
  CREATE POLICY "public read portfolio" ON public.barber_portfolio FOR SELECT TO anon, authenticated USING (true);

  DROP POLICY IF EXISTS "public read schedules" ON public.schedules;
  CREATE POLICY "public read schedules" ON public.schedules FOR SELECT TO anon, authenticated USING (true);

  DROP POLICY IF EXISTS "public read time_off" ON public.time_off;
  CREATE POLICY "public read time_off" ON public.time_off FOR SELECT TO anon, authenticated USING (true);

  DROP POLICY IF EXISTS "public read holidays" ON public.holidays;
  CREATE POLICY "public read holidays" ON public.holidays FOR SELECT TO anon, authenticated USING (true);

  DROP POLICY IF EXISTS "public read shop_settings" ON public.shop_settings;
  CREATE POLICY "public read shop_settings" ON public.shop_settings FOR SELECT TO anon, authenticated USING (true);

  -- 3) Customer bookings policies
  DROP POLICY IF EXISTS "users read own bookings" ON public.bookings;
  CREATE POLICY "users read own bookings" ON public.bookings FOR SELECT TO authenticated USING (user_id = auth.uid());

  DROP POLICY IF EXISTS "users cancel own pending" ON public.bookings;
  CREATE POLICY "users cancel own pending" ON public.bookings
    FOR UPDATE TO authenticated
    USING (user_id = auth.uid() AND status = 'pending')
    WITH CHECK (user_id = auth.uid() AND status IN ('pending','cancelled'));

  -- 4) Slot availability RPC
  CREATE OR REPLACE FUNCTION public.get_available_slots(
    p_barber_id uuid,
    p_date date,
    p_duration_minutes integer
  ) RETURNS SETOF time
  LANGUAGE plpgsql
  STABLE
  SECURITY DEFINER
  SET search_path = public
  AS $$
  DECLARE
    v_dow integer;
    v_schedule record;
    v_slot time;
    v_step interval := interval '30 minutes';
    v_duration interval;
  BEGIN
    v_duration := make_interval(mins => p_duration_minutes);
    v_dow := EXTRACT(DOW FROM p_date)::int;

    -- Holiday check
    IF EXISTS (SELECT 1 FROM public.holidays WHERE holiday_date = p_date) THEN RETURN; END IF;

    -- Time-off check
    IF EXISTS (
      SELECT 1 FROM public.time_off
      WHERE barber_id = p_barber_id
        AND p_date BETWEEN start_date AND end_date
    ) THEN RETURN; END IF;

    SELECT * INTO v_schedule FROM public.schedules
      WHERE barber_id = p_barber_id AND day_of_week = v_dow AND is_off = false
      LIMIT 1;
    IF NOT FOUND THEN RETURN; END IF;

    v_slot := v_schedule.start_time;
    WHILE (v_slot + v_duration) <= v_schedule.end_time LOOP
      -- skip past times if date is today
      IF p_date > CURRENT_DATE OR (p_date = CURRENT_DATE AND v_slot > CURRENT_TIME) THEN
        -- check for conflicting booking
        IF NOT EXISTS (
          SELECT 1 FROM public.bookings b
          JOIN public.services s ON s.id = b.service_id
          WHERE b.barber_id = p_barber_id
            AND b.booking_date = p_date
            AND b.status IN ('pending','confirmed')
            AND tstzrange(
                  (p_date + v_slot)::timestamptz,
                  (p_date + v_slot)::timestamptz + v_duration,
                  '[)'
                ) && tstzrange(
                  (b.booking_date + b.start_time)::timestamptz,
                  (b.booking_date + b.start_time)::timestamptz + make_interval(mins => s.duration_minutes),
                  '[)'
                )
        ) THEN
          RETURN NEXT v_slot;
        END IF;
      END IF;
      v_slot := v_slot + v_step;
    END LOOP;
  END;
  $$;

  GRANT EXECUTE ON FUNCTION public.get_available_slots(uuid, date, integer) TO anon, authenticated;

  -- 5) Booking creation RPC (security definer; validates and inserts)
  CREATE OR REPLACE FUNCTION public.public_booking_create(
    p_service_id uuid,
    p_barber_id uuid,
    p_booking_date date,
    p_start_time time,
    p_customer_name text,
    p_customer_phone text,
    p_customer_email text,
    p_notes text DEFAULT NULL
  ) RETURNS public.bookings
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
  DECLARE
    v_service public.services;
    v_barber public.barbers;
    v_actual_barber uuid := p_barber_id;
    v_slots time[];
    v_ref text;
    v_row public.bookings;
  BEGIN
    -- Validate input lengths
    IF length(coalesce(p_customer_name,'')) < 2 OR length(p_customer_name) > 100 THEN
      RAISE EXCEPTION 'Invalid name';
    END IF;
    IF length(coalesce(p_customer_phone,'')) < 5 OR length(p_customer_phone) > 30 THEN
      RAISE EXCEPTION 'Invalid phone';
    END IF;

    SELECT * INTO v_service FROM public.services WHERE id = p_service_id AND is_active = true;
    IF NOT FOUND THEN RAISE EXCEPTION 'Service not available'; END IF;

    -- "Any available" if barber is null: pick first barber with slot open
    IF v_actual_barber IS NULL THEN
      SELECT b.id INTO v_actual_barber
      FROM public.barbers b
      WHERE b.is_active = true
        AND p_start_time = ANY(
          SELECT * FROM public.get_available_slots(b.id, p_booking_date, v_service.duration_minutes)
        )
      ORDER BY random()
      LIMIT 1;
      IF v_actual_barber IS NULL THEN RAISE EXCEPTION 'No barber available for that time'; END IF;
    ELSE
      SELECT * INTO v_barber FROM public.barbers WHERE id = v_actual_barber AND is_active = true;
      IF NOT FOUND THEN RAISE EXCEPTION 'Barber not available'; END IF;
      SELECT array_agg(s) INTO v_slots FROM public.get_available_slots(v_actual_barber, p_booking_date, v_service.duration_minutes) s;
      IF v_slots IS NULL OR NOT (p_start_time = ANY(v_slots)) THEN
        RAISE EXCEPTION 'Selected time is no longer available';
      END IF;
    END IF;

    v_ref := 'BK-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 6));

    INSERT INTO public.bookings (
      reference, customer_name, customer_phone, customer_email,
      barber_id, service_id, booking_date, start_time, status, price, notes, user_id
    ) VALUES (
      v_ref, p_customer_name, p_customer_phone, nullif(p_customer_email,''),
      v_actual_barber, p_service_id, p_booking_date, p_start_time, 'pending', v_service.price, p_notes, auth.uid()
    ) RETURNING * INTO v_row;

    RETURN v_row;
  END;
  $$;

  GRANT EXECUTE ON FUNCTION public.public_booking_create(uuid, uuid, date, time, text, text, text, text) TO anon, authenticated;


  -- ====================================================================================
  -- MIGRATION 4: 20260619110848_ffb1826f-5997-4ab0-ba39-c95a808706e8.sql
  -- ====================================================================================

  -- 1) audit_logs table
  CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_user_id uuid,
    actor_email text,
    actor_role text,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id uuid,
    summary text,
    before jsonb,
    after jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
  );

  CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.audit_logs (entity_type, entity_id);
  CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON public.audit_logs (actor_user_id);
  CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.audit_logs (action);

  GRANT SELECT ON public.audit_logs TO authenticated;
  GRANT ALL ON public.audit_logs TO service_role;

  ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "Admins can view audit logs" ON public.audit_logs;
  CREATE POLICY "Admins can view audit logs"
    ON public.audit_logs
    FOR SELECT
    TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));

  -- 2) Helper to resolve actor email + role
  CREATE OR REPLACE FUNCTION public._audit_actor()
  RETURNS TABLE (uid uuid, email text, role text)
  LANGUAGE plpgsql
  STABLE SECURITY DEFINER
  SET search_path = public
  AS $$
  DECLARE
    v_uid uuid := auth.uid();
    v_email text;
    v_role text;
  BEGIN
    IF v_uid IS NULL THEN
      RETURN QUERY SELECT NULL::uuid, 'guest'::text, 'guest'::text;
      RETURN;
    END IF;
    SELECT u.email INTO v_email FROM auth.users u WHERE u.id = v_uid;
    IF public.has_role(v_uid, 'admin') THEN v_role := 'admin';
    ELSIF public.has_role(v_uid, 'staff') THEN v_role := 'staff';
    ELSE v_role := 'customer';
    END IF;
    RETURN QUERY SELECT v_uid, v_email, v_role;
  END;
  $$;

  -- 3) Generic trigger writer
  CREATE OR REPLACE FUNCTION public._audit_write(
    p_action text,
    p_entity_type text,
    p_entity_id uuid,
    p_summary text,
    p_before jsonb,
    p_after jsonb
  ) RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
  DECLARE a record;
  BEGIN
    SELECT * INTO a FROM public._audit_actor();
    INSERT INTO public.audit_logs(actor_user_id, actor_email, actor_role, action, entity_type, entity_id, summary, before, after)
    VALUES (a.uid, a.email, a.role, p_action, p_entity_type, p_entity_id, p_summary, p_before, p_after);
  END;
  $$;

  -- 4) Bookings trigger
  CREATE OR REPLACE FUNCTION public.tg_audit_bookings()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
  DECLARE v_summary text;
  BEGIN
    IF TG_OP = 'INSERT' THEN
      v_summary := 'Booking ' || COALESCE(NEW.reference,'') || ' created for ' || COALESCE(NEW.customer_name,'(unknown)');
      PERFORM public._audit_write('booking.created','booking',NEW.id,v_summary,NULL,to_jsonb(NEW));
      RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
      IF NEW.status IS DISTINCT FROM OLD.status THEN
        v_summary := 'Booking ' || COALESCE(NEW.reference,'') || ' status: ' || OLD.status || ' → ' || NEW.status;
        PERFORM public._audit_write('booking.status_changed','booking',NEW.id,v_summary,to_jsonb(OLD),to_jsonb(NEW));
      ELSE
        v_summary := 'Booking ' || COALESCE(NEW.reference,'') || ' updated';
        PERFORM public._audit_write('booking.updated','booking',NEW.id,v_summary,to_jsonb(OLD),to_jsonb(NEW));
      END IF;
      RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
      v_summary := 'Booking ' || COALESCE(OLD.reference,'') || ' deleted';
      PERFORM public._audit_write('booking.deleted','booking',OLD.id,v_summary,to_jsonb(OLD),NULL);
      RETURN OLD;
    END IF;
    RETURN NULL;
  END;
  $$;
  DROP TRIGGER IF EXISTS audit_bookings ON public.bookings;
  CREATE TRIGGER audit_bookings AFTER INSERT OR UPDATE OR DELETE ON public.bookings
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_bookings();

  -- 5) Walk-ins trigger
  CREATE OR REPLACE FUNCTION public.tg_audit_walk_ins()
  RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
  AS $$
  DECLARE v_summary text; v_id uuid; v_name text;
  BEGIN
    IF TG_OP = 'INSERT' THEN
      PERFORM public._audit_write('walk_in.created','walk_in',NEW.id,
        'Walk-in added for ' || COALESCE(NEW.customer_name,'(unknown)'), NULL, to_jsonb(NEW));
      RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
      IF NEW.status IS DISTINCT FROM OLD.status THEN
        v_summary := 'Walk-in ' || COALESCE(NEW.customer_name,'') || ' status: ' || OLD.status || ' → ' || NEW.status;
        PERFORM public._audit_write('walk_in.status_changed','walk_in',NEW.id,v_summary,to_jsonb(OLD),to_jsonb(NEW));
      ELSE
        PERFORM public._audit_write('walk_in.updated','walk_in',NEW.id,
          'Walk-in ' || COALESCE(NEW.customer_name,'') || ' updated', to_jsonb(OLD), to_jsonb(NEW));
      END IF;
      RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
      PERFORM public._audit_write('walk_in.deleted','walk_in',OLD.id,
        'Walk-in ' || COALESCE(OLD.customer_name,'') || ' deleted', to_jsonb(OLD), NULL);
      RETURN OLD;
    END IF;
    RETURN NULL;
  END;
  $$;
  DROP TRIGGER IF EXISTS audit_walk_ins ON public.walk_ins;
  CREATE TRIGGER audit_walk_ins AFTER INSERT OR UPDATE OR DELETE ON public.walk_ins
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_walk_ins();

  -- 6) Generic table trigger factory: services, barbers, schedules, holidays, time_off, shop_settings
  CREATE OR REPLACE FUNCTION public.tg_audit_generic()
  RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
  AS $$
  DECLARE
    v_entity text := TG_ARGV[0];
    v_label_col text := TG_ARGV[1]; -- column to use in summary
    v_label text;
    v_id uuid;
    v_op text;
  BEGIN
    IF TG_OP = 'DELETE' THEN
      EXECUTE format('SELECT ($1).%I::text', v_label_col) INTO v_label USING OLD;
      v_id := (to_jsonb(OLD) ->> 'id')::uuid;
      PERFORM public._audit_write(v_entity || '.deleted', v_entity, v_id,
        initcap(v_entity) || ' "' || COALESCE(v_label,'') || '" deleted', to_jsonb(OLD), NULL);
      RETURN OLD;
    ELSIF TG_OP = 'INSERT' THEN
      EXECUTE format('SELECT ($1).%I::text', v_label_col) INTO v_label USING NEW;
      v_id := (to_jsonb(NEW) ->> 'id')::uuid;
      PERFORM public._audit_write(v_entity || '.created', v_entity, v_id,
        initcap(v_entity) || ' "' || COALESCE(v_label,'') || '" created', NULL, to_jsonb(NEW));
      RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
      EXECUTE format('SELECT ($1).%I::text', v_label_col) INTO v_label USING NEW;
      v_id := (to_jsonb(NEW) ->> 'id')::uuid;
      PERFORM public._audit_write(v_entity || '.updated', v_entity, v_id,
        initcap(v_entity) || ' "' || COALESCE(v_label,'') || '" updated', to_jsonb(OLD), to_jsonb(NEW));
      RETURN NEW;
    END IF;
    RETURN NULL;
  END;
  $$;

  DROP TRIGGER IF EXISTS audit_services ON public.services;
  CREATE TRIGGER audit_services AFTER INSERT OR UPDATE OR DELETE ON public.services
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_generic('service','name');

  DROP TRIGGER IF EXISTS audit_barbers ON public.barbers;
  CREATE TRIGGER audit_barbers AFTER INSERT OR UPDATE OR DELETE ON public.barbers
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_generic('barber','name');

  DROP TRIGGER IF EXISTS audit_schedules ON public.schedules;
  CREATE TRIGGER audit_schedules AFTER INSERT OR UPDATE OR DELETE ON public.schedules
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_generic('schedule','barber_id');

  DROP TRIGGER IF EXISTS audit_holidays ON public.holidays;
  CREATE TRIGGER audit_holidays AFTER INSERT OR UPDATE OR DELETE ON public.holidays
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_generic('holiday','name');

  DROP TRIGGER IF EXISTS audit_time_off ON public.time_off;
  CREATE TRIGGER audit_time_off AFTER INSERT OR UPDATE OR DELETE ON public.time_off
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_generic('time_off','barber_id');

  DROP TRIGGER IF EXISTS audit_shop_settings ON public.shop_settings;
  CREATE TRIGGER audit_shop_settings AFTER INSERT OR UPDATE OR DELETE ON public.shop_settings
    FOR EACH ROW EXECUTE FUNCTION public.tg_audit_generic('shop_settings','shop_name');


  -- ====================================================================================
  -- MIGRATION 5: 20260619110916_453aad1f-3699-4f91-b0a4-378290da827b.sql
  -- ====================================================================================

  REVOKE ALL ON FUNCTION public._audit_actor() FROM PUBLIC, anon, authenticated;
  REVOKE ALL ON FUNCTION public._audit_write(text,text,uuid,text,jsonb,jsonb) FROM PUBLIC, anon, authenticated;
  REVOKE ALL ON FUNCTION public.tg_audit_bookings() FROM PUBLIC, anon, authenticated;
  REVOKE ALL ON FUNCTION public.tg_audit_walk_ins() FROM PUBLIC, anon, authenticated;
  REVOKE ALL ON FUNCTION public.tg_audit_generic() FROM PUBLIC, anon, authenticated;


  -- ====================================================================================
  -- MIGRATION 6: 20260626000000_audit_logs_retention.sql
  -- ====================================================================================

  -- 1. Function that deletes expired rows
  CREATE OR REPLACE FUNCTION public.delete_expired_audit_logs()
  RETURNS void
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path = public
  AS $$
    DELETE FROM public.audit_logs
    WHERE created_at < now() - INTERVAL '3 months';
  $$;

  -- 2. Schedule the function to run once a day using pg_cron (Safely handled if extension not enabled)
  DO $$
  BEGIN
    CREATE EXTENSION IF NOT EXISTS pg_cron;
    PERFORM cron.schedule(
      'delete-expired-audit-logs',   -- job name (unique)
      '0 3 * * *',                   -- every day at 3 AM UTC
      'SELECT public.delete_expired_audit_logs();'
    );
  EXCEPTION
    WHEN OTHERS THEN
      RAISE NOTICE 'pg_cron not available or schedule failed, skipping cron setup: %', SQLERRM;
  END $$;


  -- ====================================================================================
  -- MIGRATION 7: 20260628084609_03e32b75-137c-483b-a11a-7bb615a99626.sql
  -- ====================================================================================

  -- 1. shop_settings: restrict public SELECT to a fixed list of safe columns
  REVOKE SELECT ON public.shop_settings FROM anon, authenticated;
  GRANT SELECT (id, shop_name, shop_address, shop_phone, shop_email, open_time, close_time, payment_cash, payment_gcash, payment_maya, payment_card, updated_at) ON public.shop_settings TO anon, authenticated;

  -- 2. notifications: confirm admin-only intent
  COMMENT ON TABLE public.notifications IS 'Admin-only operational notifications. No user_id column by design; not user-facing. Only admins can read/write via RLS.';

  -- 3. Lock down internal SECURITY DEFINER helpers — they should not be callable via the API
  REVOKE EXECUTE ON FUNCTION public._audit_actor() FROM PUBLIC, anon, authenticated;
  REVOKE EXECUTE ON FUNCTION public._audit_write(text, text, uuid, text, jsonb, jsonb) FROM PUBLIC, anon, authenticated;
  REVOKE EXECUTE ON FUNCTION public.tg_audit_bookings() FROM PUBLIC, anon, authenticated;
  REVOKE EXECUTE ON FUNCTION public.tg_audit_walk_ins() FROM PUBLIC, anon, authenticated;
  REVOKE EXECUTE ON FUNCTION public.tg_audit_generic() FROM PUBLIC, anon, authenticated;
  REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

  -- has_role is used inside RLS policies; signed-in users need EXECUTE so policies evaluate. Revoke from anon only.
  REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC, anon;


  -- ====================================================================================
  -- MIGRATION 8: 20260628135819_bbb79bf0-784c-4666-b74e-489913a2d74d.sql
  -- ====================================================================================

  CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    full_name text,
    phone text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  );

  GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated;
  GRANT ALL ON public.profiles TO service_role;

  ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "Profiles viewable by owner, admin, or staff" ON public.profiles;
  CREATE POLICY "Profiles viewable by owner, admin, or staff"
    ON public.profiles FOR SELECT TO authenticated
    USING (
      auth.uid() = id
      OR public.has_role(auth.uid(), 'admin')
      OR public.has_role(auth.uid(), 'staff')
    );

  DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
  CREATE POLICY "Users update own profile"
    ON public.profiles FOR UPDATE TO authenticated
    USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

  CREATE OR REPLACE FUNCTION public.update_updated_at_column()
  RETURNS TRIGGER AS $$
  BEGIN NEW.updated_at = now(); RETURN NEW; END;
  $$ LANGUAGE plpgsql SET search_path = public;

  DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
  CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

  -- Extend existing handle_new_user to also insert profile
  CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.user_roles WHERE role = 'admin') THEN
      INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'admin') ON CONFLICT DO NOTHING;
    ELSE
      INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'staff') ON CONFLICT DO NOTHING;
    END IF;

    INSERT INTO public.profiles (id, email, full_name, phone)
    VALUES (
      NEW.id,
      NEW.email,
      NEW.raw_user_meta_data->>'full_name',
      NEW.raw_user_meta_data->>'phone'
    )
    ON CONFLICT (id) DO NOTHING;

    RETURN NEW;
  END;
  $function$;

  -- Backfill
  INSERT INTO public.profiles (id, email, full_name, phone)
  SELECT u.id, u.email,
        u.raw_user_meta_data->>'full_name',
        u.raw_user_meta_data->>'phone'
  FROM auth.users u
  ON CONFLICT (id) DO NOTHING;


  -- ====================================================================================
  -- MIGRATION 9: 20260628183751_521f2b31-f1d5-4e9a-bc2e-70a3fcccf4e1.sql
  -- ====================================================================================

  -- 1) time_off.reason — restrict column visibility
  REVOKE SELECT ON public.time_off FROM anon, authenticated;
  GRANT SELECT (id, barber_id, start_date, end_date, created_at) ON public.time_off TO anon, authenticated;
  GRANT SELECT ON public.time_off TO service_role;

  CREATE OR REPLACE VIEW public.time_off_admin
  WITH (security_invoker = true) AS
  SELECT * FROM public.time_off
  WHERE public.has_role(auth.uid(), 'admin');

  GRANT SELECT ON public.time_off_admin TO authenticated;

  -- 2) walk_ins — add explicit staff SELECT policy
  DROP POLICY IF EXISTS "staff read walk_ins" ON public.walk_ins;
  CREATE POLICY "staff read walk_ins"
  ON public.walk_ins
  FOR SELECT
  TO authenticated
  USING (public.has_role(auth.uid(), 'staff') OR public.has_role(auth.uid(), 'admin'));


  -- ====================================================================================
  -- MIGRATION 10: 20260703082942_47462453-18c3-44af-882b-d943c6fab999.sql
  -- ====================================================================================

  -- Add queue-tracking columns
  ALTER TABLE public.walk_ins
    ADD COLUMN IF NOT EXISTS queue_number int,
    ADD COLUMN IF NOT EXISTS served_at timestamptz,
    ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS customer_email text;

  -- Per-day queue number trigger
  CREATE OR REPLACE FUNCTION public.tg_assign_queue_number()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
  BEGIN
    IF NEW.queue_number IS NULL THEN
      SELECT COALESCE(MAX(queue_number), 0) + 1
        INTO NEW.queue_number
      FROM public.walk_ins
      WHERE (created_at AT TIME ZONE 'UTC')::date = (COALESCE(NEW.created_at, now()) AT TIME ZONE 'UTC')::date;
    END IF;
    RETURN NEW;
  END;
  $$;

  DROP TRIGGER IF EXISTS assign_queue_number ON public.walk_ins;
  CREATE TRIGGER assign_queue_number
    BEFORE INSERT ON public.walk_ins
    FOR EACH ROW EXECUTE FUNCTION public.tg_assign_queue_number();

  -- Stamp served_at on completion
  CREATE OR REPLACE FUNCTION public.tg_stamp_served_at()
  RETURNS trigger
  LANGUAGE plpgsql
  SET search_path = public
  AS $$
  BEGIN
    IF NEW.status = 'completed' AND OLD.status <> 'completed' AND NEW.served_at IS NULL THEN
      NEW.served_at := now();
    END IF;
    RETURN NEW;
  END;
  $$;

  DROP TRIGGER IF EXISTS stamp_served_at ON public.walk_ins;
  CREATE TRIGGER stamp_served_at
    BEFORE UPDATE ON public.walk_ins
    FOR EACH ROW EXECUTE FUNCTION public.tg_stamp_served_at();

  -- Backfill queue numbers for existing rows
  WITH ordered AS (
    SELECT id, ROW_NUMBER() OVER (PARTITION BY (created_at AT TIME ZONE 'UTC')::date ORDER BY created_at) AS rn
    FROM public.walk_ins
    WHERE queue_number IS NULL
  )
  UPDATE public.walk_ins w
  SET queue_number = o.rn
  FROM ordered o
  WHERE w.id = o.id;

  -- Public safe view: only first name + queue info, today only
  CREATE OR REPLACE VIEW public.queue_public
  WITH (security_invoker = true)
  AS
  SELECT
    id,
    queue_number,
    split_part(customer_name, ' ', 1) AS first_name,
    status::text AS status,
    created_at,
    served_at
  FROM public.walk_ins
  WHERE (created_at AT TIME ZONE 'UTC')::date = (now() AT TIME ZONE 'UTC')::date;

  GRANT SELECT ON public.queue_public TO anon, authenticated;

  REVOKE ALL ON public.walk_ins FROM anon;
  GRANT SELECT (id, queue_number, customer_name, status, created_at, served_at) ON public.walk_ins TO anon;

  DROP POLICY IF EXISTS "anon read today queue" ON public.walk_ins;
  CREATE POLICY "anon read today queue" ON public.walk_ins
    FOR SELECT
    TO anon
    USING ((created_at AT TIME ZONE 'UTC')::date = (now() AT TIME ZONE 'UTC')::date);

  DROP POLICY IF EXISTS "auth read today queue" ON public.walk_ins;
  CREATE POLICY "auth read today queue" ON public.walk_ins
    FOR SELECT
    TO authenticated
    USING ((created_at AT TIME ZONE 'UTC')::date = (now() AT TIME ZONE 'UTC')::date);

  -- Lookup RPC for attendants: find a customer by email
  CREATE OR REPLACE FUNCTION public.lookup_customer_by_email(p_email text)
  RETURNS TABLE(user_id uuid, full_name text, email text, phone text)
  LANGUAGE plpgsql
  STABLE
  SECURITY DEFINER
  SET search_path = public
  AS $$
  BEGIN
    IF NOT (public.has_role(auth.uid(), 'admin') OR public.has_role(auth.uid(), 'staff')) THEN
      RAISE EXCEPTION 'Not authorized';
    END IF;
    RETURN QUERY
      SELECT p.id, p.full_name, p.email, p.phone
      FROM public.profiles p
      WHERE lower(p.email) = lower(trim(p_email))
      LIMIT 1;
  END;
  $$;

  REVOKE ALL ON FUNCTION public.lookup_customer_by_email(text) FROM PUBLIC, anon;
  GRANT EXECUTE ON FUNCTION public.lookup_customer_by_email(text) TO authenticated;

  -- Realtime
  ALTER TABLE public.walk_ins REPLICA IDENTITY FULL;
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'walk_ins'
    ) THEN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.walk_ins;
    END IF;
  END $$;


  -- ====================================================================================
  -- MIGRATION 11: 20260703083409_fbdb3bde-a21a-46d0-8498-f78cf5993879.sql
  -- ====================================================================================

  -- Allow authenticated users to read their own walk_in queue entry so they can see position on /queue
  DROP POLICY IF EXISTS "Users can view own walk_in entries" ON public.walk_ins;
  CREATE POLICY "Users can view own walk_in entries"
    ON public.walk_ins
    FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());


  -- ====================================================================================
  -- MIGRATION 12: 20260703091423_a35ab960-a7c3-4907-af7e-75408482ee5a.sql
  -- ====================================================================================

  -- Recreate queue_public view including duration_minutes for wait math
  DROP VIEW IF EXISTS public.queue_public;
  CREATE VIEW public.queue_public
  WITH (security_invoker = true)
  AS
  SELECT
    w.id,
    w.queue_number,
    split_part(coalesce(w.customer_name, 'Guest'), ' ', 1) AS first_name,
    w.status,
    w.created_at,
    w.served_at,
    w.service_id,
    COALESCE(s.duration_minutes, 30) AS duration_minutes
  FROM public.walk_ins w
  LEFT JOIN public.services s ON s.id = w.service_id
  WHERE (w.created_at AT TIME ZONE 'UTC')::date = (now() AT TIME ZONE 'UTC')::date
    AND w.status IN ('waiting', 'in_progress');

  GRANT SELECT ON public.queue_public TO anon, authenticated;

  -- Allow authenticated users to see their own walk_ins row
  DO $$
  BEGIN
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
      WHERE schemaname = 'public' AND tablename = 'walk_ins' AND policyname = 'Users can view their own walk_ins'
    ) THEN
      CREATE POLICY "Users can view their own walk_ins"
      ON public.walk_ins FOR SELECT
      TO authenticated
      USING (auth.uid() = user_id);
    END IF;
  END $$;


  -- ====================================================================================
  -- MIGRATION 13: 20260703091626_14517786-d83d-4b1e-bf4a-6ba812d8caa6.sql
  -- ====================================================================================

  DROP POLICY IF EXISTS "anon read today queue" ON public.walk_ins;
  DROP POLICY IF EXISTS "auth read today queue" ON public.walk_ins;


  -- ====================================================================================
  -- MIGRATION 14: 20260704055959_fc17cc90-bcc3-4e13-8578-28049d7ef44e.sql
  -- ====================================================================================

  -- Recreate queue_public as a SECURITY DEFINER view so anon/authenticated
  -- can read the safe today's-queue projection without needing per-row RLS
  -- or column-level grants on public.walk_ins.
  DROP VIEW IF EXISTS public.queue_public;

  CREATE VIEW public.queue_public
  WITH (security_invoker = false) AS
  SELECT
    w.id,
    w.queue_number,
    split_part(coalesce(w.customer_name, ''), ' ', 1) AS first_name,
    w.status,
    w.created_at,
    w.served_at,
    w.service_id,
    COALESCE(s.duration_minutes, 30) AS duration_minutes
  FROM public.walk_ins w
  LEFT JOIN public.services s ON s.id = w.service_id
  WHERE (w.created_at AT TIME ZONE 'UTC')::date = (now() AT TIME ZONE 'UTC')::date
    AND w.status IN ('waiting', 'in_progress');

  GRANT SELECT ON public.queue_public TO anon, authenticated;

  -- ====================================================================================
  -- MIGRATION 15: 20260704194500_create_reviews.sql
  -- ====================================================================================

  CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id UUID REFERENCES public.bookings(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    service_name TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
  );

  GRANT SELECT, INSERT ON public.reviews TO anon, authenticated;
  GRANT ALL ON public.reviews TO service_role;
  ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

  DROP POLICY IF EXISTS "Anyone can read reviews" ON public.reviews;
  CREATE POLICY "Anyone can read reviews" ON public.reviews FOR SELECT TO anon, authenticated USING (true);

  DROP POLICY IF EXISTS "Anyone can insert reviews" ON public.reviews;
  CREATE POLICY "Anyone can insert reviews" ON public.reviews FOR INSERT TO anon, authenticated WITH CHECK (true);

  -- ====================================================================================
  -- MIGRATION 16: 20260704205600_add_barber_to_reviews.sql
  -- ====================================================================================

  ALTER TABLE public.reviews
  ADD COLUMN IF NOT EXISTS barber_id UUID REFERENCES public.barbers(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS barber_name TEXT;



  -- ====================================================================================
  -- MIGRATION 15: 20260706120000_barber_ratings_and_storage.sql
  -- ====================================================================================

  -- ============================================================
  -- 1. Auto-calculate barber rating from customer reviews
  --    (removes the need for admins to type a rating manually)
  -- ============================================================

  CREATE OR REPLACE FUNCTION public.recalculate_barber_rating()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = public
  AS $$
  DECLARE
    target_barber_id UUID;
    new_rating NUMERIC;
  BEGIN
    target_barber_id := COALESCE(NEW.barber_id, OLD.barber_id);

    IF target_barber_id IS NULL THEN
      RETURN COALESCE(NEW, OLD);
    END IF;

    SELECT COALESCE(ROUND(AVG(rating)::numeric, 2), 5.0)
    INTO new_rating
    FROM public.reviews
    WHERE barber_id = target_barber_id;

    UPDATE public.barbers
    SET rating = new_rating
    WHERE id = target_barber_id;

    RETURN COALESCE(NEW, OLD);
  END;
  $$;

  DROP TRIGGER IF EXISTS reviews_recalculate_barber_rating ON public.reviews;
  CREATE TRIGGER reviews_recalculate_barber_rating
  AFTER INSERT OR UPDATE OF rating, barber_id OR DELETE ON public.reviews
  FOR EACH ROW EXECUTE FUNCTION public.recalculate_barber_rating();

  -- Backfill ratings for barbers that already have reviews
  UPDATE public.barbers b
  SET rating = COALESCE(
    (SELECT ROUND(AVG(r.rating)::numeric, 2) FROM public.reviews r WHERE r.barber_id = b.id),
    b.rating
  );

  -- ============================================================
  -- 2. Storage buckets for barber avatar + portfolio photo uploads
  --    (replaces manual "paste a URL" fields with real file uploads)
  -- ============================================================

  INSERT INTO storage.buckets (id, name, public)
  VALUES ('barber-avatars', 'barber-avatars', true)
  ON CONFLICT (id) DO NOTHING;

  INSERT INTO storage.buckets (id, name, public)
  VALUES ('barber-portfolio', 'barber-portfolio', true)
  ON CONFLICT (id) DO NOTHING;

  -- Anyone can view the images (they're shown on the public site)
  DROP POLICY IF EXISTS "Public read barber avatars" ON storage.objects;
  CREATE POLICY "Public read barber avatars"
    ON storage.objects FOR SELECT TO anon, authenticated
    USING (bucket_id = 'barber-avatars');

  DROP POLICY IF EXISTS "Public read barber portfolio" ON storage.objects;
  CREATE POLICY "Public read barber portfolio"
    ON storage.objects FOR SELECT TO anon, authenticated
    USING (bucket_id = 'barber-portfolio');

  -- Only admins can upload / replace / remove images
  DROP POLICY IF EXISTS "Admins upload barber avatars" ON storage.objects;
  CREATE POLICY "Admins upload barber avatars"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'barber-avatars' AND public.has_role(auth.uid(), 'admin'));

  DROP POLICY IF EXISTS "Admins update barber avatars" ON storage.objects;
  CREATE POLICY "Admins update barber avatars"
    ON storage.objects FOR UPDATE TO authenticated
    USING (bucket_id = 'barber-avatars' AND public.has_role(auth.uid(), 'admin'));

  DROP POLICY IF EXISTS "Admins delete barber avatars" ON storage.objects;
  CREATE POLICY "Admins delete barber avatars"
    ON storage.objects FOR DELETE TO authenticated
    USING (bucket_id = 'barber-avatars' AND public.has_role(auth.uid(), 'admin'));

  DROP POLICY IF EXISTS "Admins upload barber portfolio" ON storage.objects;
  CREATE POLICY "Admins upload barber portfolio"
    ON storage.objects FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'barber-portfolio' AND public.has_role(auth.uid(), 'admin'));

  DROP POLICY IF EXISTS "Admins update barber portfolio" ON storage.objects;
  CREATE POLICY "Admins update barber portfolio"
    ON storage.objects FOR UPDATE TO authenticated
    USING (bucket_id = 'barber-portfolio' AND public.has_role(auth.uid(), 'admin'));

  DROP POLICY IF EXISTS "Admins delete barber portfolio" ON storage.objects;
  CREATE POLICY "Admins delete barber portfolio"
    ON storage.objects FOR DELETE TO authenticated
    USING (bucket_id = 'barber-portfolio' AND public.has_role(auth.uid(), 'admin'));
