/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BarbersRouteImport } from './routes/barbers'
import { Route as BarberTestRouteImport } from './routes/barber-test'
import { Route as BarberRouteImport } from './routes/barber'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWalkInsRouteImport } from './routes/admin/walk-ins'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSchedulesRouteImport } from './routes/admin/schedules'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCharitiesRouteImport } from './routes/admin/charities'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminBarbersRouteImport } from './routes/admin/barbers'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersRoute = BarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberTestRoute = BarberTestRouteImport.update({
  id: '/barber-test',
  path: '/barber-test',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberRoute = BarberRouteImport.update({
  id: '/barber',
  path: '/barber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWalkInsRoute = AdminWalkInsRouteImport.update({
  id: '/walk-ins',
  path: '/walk-ins',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCharitiesRoute = AdminCharitiesRouteImport.update({
  id: '/charities',
  path: '/charities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBarbersRoute = AdminBarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRoute
  '/barber-test': typeof BarberTestRoute
  '/barbers': typeof BarbersRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/my-bookings': typeof MyBookingsRoute
  '/queue': typeof QueueRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/barbers': typeof AdminBarbersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/charities': typeof AdminCharitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/walk-ins': typeof AdminWalkInsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRoute
  '/barber-test': typeof BarberTestRoute
  '/barbers': typeof BarbersRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/my-bookings': typeof MyBookingsRoute
  '/queue': typeof QueueRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/barbers': typeof AdminBarbersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/charities': typeof AdminCharitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/walk-ins': typeof AdminWalkInsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/barber': typeof BarberRoute
  '/barber-test': typeof BarberTestRoute
  '/barbers': typeof BarbersRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/my-bookings': typeof MyBookingsRoute
  '/queue': typeof QueueRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/barbers': typeof AdminBarbersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/charities': typeof AdminCharitiesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/walk-ins': typeof AdminWalkInsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/barber'
    | '/barber-test'
    | '/barbers'
    | '/book'
    | '/contact'
    | '/my-bookings'
    | '/queue'
    | '/reset-password'
    | '/reviews'
    | '/services'
    | '/admin/audit-logs'
    | '/admin/barbers'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/charities'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/schedules'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/walk-ins'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/barber'
    | '/barber-test'
    | '/barbers'
    | '/book'
    | '/contact'
    | '/my-bookings'
    | '/queue'
    | '/reset-password'
    | '/reviews'
    | '/services'
    | '/admin/audit-logs'
    | '/admin/barbers'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/charities'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/schedules'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/walk-ins'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/auth'
    | '/barber'
    | '/barber-test'
    | '/barbers'
    | '/book'
    | '/contact'
    | '/my-bookings'
    | '/queue'
    | '/reset-password'
    | '/reviews'
    | '/services'
    | '/admin/audit-logs'
    | '/admin/barbers'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/charities'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/schedules'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/walk-ins'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BarberRoute: typeof BarberRoute
  BarberTestRoute: typeof BarberTestRoute
  BarbersRoute: typeof BarbersRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  MyBookingsRoute: typeof MyBookingsRoute
  QueueRoute: typeof QueueRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers': {
      id: '/barbers'
      path: '/barbers'
      fullPath: '/barbers'
      preLoaderRoute: typeof BarbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber-test': {
      id: '/barber-test'
      path: '/barber-test'
      fullPath: '/barber-test'
      preLoaderRoute: typeof BarberTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber': {
      id: '/barber'
      path: '/barber'
      fullPath: '/barber'
      preLoaderRoute: typeof BarberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/walk-ins': {
      id: '/admin/walk-ins'
      path: '/walk-ins'
      fullPath: '/admin/walk-ins'
      preLoaderRoute: typeof AdminWalkInsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/charities': {
      id: '/admin/charities'
      path: '/charities'
      fullPath: '/admin/charities'
      preLoaderRoute: typeof AdminCharitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/barbers': {
      id: '/admin/barbers'
      path: '/barbers'
      fullPath: '/admin/barbers'
      preLoaderRoute: typeof AdminBarbersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBarbersRoute: typeof AdminBarbersRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCharitiesRoute: typeof AdminCharitiesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWalkInsRoute: typeof AdminWalkInsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBarbersRoute: AdminBarbersRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCharitiesRoute: AdminCharitiesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWalkInsRoute: AdminWalkInsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BarberRoute: BarberRoute,
  BarberTestRoute: BarberTestRoute,
  BarbersRoute: BarbersRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  MyBookingsRoute: MyBookingsRoute,
  QueueRoute: QueueRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
